################################# Default configuration ###################
# provide your domain here
baseURL = "https://biokic.github.io/symbiota-docs/"
# theme
theme = "dot"
# site title
title = "Symbiota Docs"
# disable language
# disableLanguages = []
# google analytics
googleAnalytics = "G-MPX39Z5FZQ" # global tag; should use universal instead
# unsafe html
[markup.goldmark.renderer]
unsafe = true
# enables creation of index for full-text search
[outputs]
   home = [ "HTML", "JSON" ]

############################# Default Parameters ##########################
[params]
editURL = "https://github.com/BioKIC/symbiota-docs/edit/master/content/"
# logo is for all page
logo = ""
# logo white is for homepage logo, you can use colorful logo too...
logo_white = ""
# when logo is empty, it will shown your site title

# customize color
#primary_color = "#02007e"
primary_color = "#428500"
body_color = "#f9f9f9"
text_color = "#636363"
text_color_dark = "#242738"
white_color = "#ffffff"
light_color = "#f8f9fa"

# font family
font_family = "lato" # Choose font family from : https://fonts.google.com/

# contact form action
#contact_form_action = "#" # contact form works #with : https://formspree.io

[[params.plugins.css]]
link = "/assets/css/custom.css"

############################## social links ##############################
[[params.social]]
# icon = "ti-facebook" # themify icon pack : https://themify.me/themify-icons
# link = "#"

[[params.social]]
# icon = "ti-twitter-alt" # themify icon pack : https://themify.me/themify-icons
# link = "#"
  
[[params.social]]
# icon = "ti-github" # themify icon pack : https://themify.me/themify-icons
# link = "#"
  
[[params.social]]
# icon = "ti-linkedin" # themify icon pack : https://themify.me/themify-icons
# link = "#"


################################ English Language ######################
[Languages.en]
languageName = "En"
languageCode = "en-us"
weight = 1
#copyright = "Put together with \u2665 by [Laura](https://laura.rochaprado.com/)"
copyright = "© 2021 [Symbiota Support Hub](https://symbiota.org)"

# banner
[Languages.en.params.banner]
title = "Symbiota Documentation"
subtitle = "Growing archive of help files for one of the most popular Natural History content management systems"
bg_image = "images/annie-spratt-5cFwQ-WMcJU-unsplash.jpg"
placeholder = "Quick search for terms here. Press enter to go to results page."

# call to action
[Languages.en.params.cta]
enable = true
title = "Still need help?"
content = ""
# call to action button
[Languages.en.params.cta.button]
enable = true
label = "contact us"
link = "contact"


################## english navigation #################
[[Languages.en.menu.main]]
name = "Home"
url = "/"
weight = 1

[[Languages.en.menu.main]]
name = "About"
url = "about"
weight = 2

[[Languages.en.menu.main]]
name = "Faq"
url = "faq"
weight = 3

[[Languages.en.menu.main]]
name = "Citing The Docs"
url = "citing"
weight = 4

[[Languages.en.menu.main]]
name = "Contact"
url = "contact"
weight = 5

[[Languages.en.menu.main]]
name = "Contributing"
url = "contribute"
weight = 6

[[Languages.en.menu.main]]
name = "Search"
pre = "<i class='ti-search search-icon'></i>"
url = "search"
weight = 7

# Dropdown menu
[[Languages.en.menu.main]]
weight = 8
name = "Docs"
hasChildren = true

  [[Languages.en.menu.main]]
  parent = "Docs"
  name = "Developer Guide"
  url = "dev"
  weight = 4

  [[Languages.en.menu.main]]
  parent = "Docs"
  name = "User Guide"
  url = "user"
  weight = 1

  [[Languages.en.menu.main]]
  parent = "Docs"
  name = "Editor Guide"
  url = "editor"
  weight = 2

  [[Languages.en.menu.main]]
  parent = "Docs"
  name = "Collection Manager Guide"
  url = "coll_manager"
  weight = 3

################################ Spanish Language ######################
[Languages.es]
languageName = "Es"
languageCode = "es"
weight = 2
copyright = "© 2021 [Symbiota Support Hub](https://symbiota.org)"

# banner
[Languages.es.params.banner]
title = "Documentación de Symbiota"
subtitle = "Un archivo creciente de documentos de ayuda para uno de los sistemas de manejo de contenido de Historia Natural más populares"
bg_image = "images/annie-spratt-5cFwQ-WMcJU-unsplash.jpg"
placeholder = "Busque contenido aquí"

# call to action
[Languages.es.params.cta]
enable = true
title = "¿Aún necesita ayuda?"
content = ""

# call to action button
[Languages.es.params.cta.button]
enable = true
label = "contáctenos"
link = "contact"


################## spanish navigation #################
[[Languages.es.menu.main]]
name = "Inicio"
url = "/"
weight = 1

[[Languages.es.menu.main]]
name = "Acerca De"
url = "about"
weight = 2

[[Languages.es.menu.main]]
name = "Faq"
url = "faq"
weight = 3

[[Languages.es.menu.main]]
name = "Citando los Documentos"
url = "citing"
weight = 4

[[Languages.es.menu.main]]
name = "Contáctenos"
url = "contact"
weight = 5

[[Languages.es.menu.main]]
name = "Contribuyendo"
url = "contribute"
weight = 6

[[Languages.es.menu.main]]
name = "Buscar"
url = "search"
weight = 7

# Dropdown menu
[[Languages.es.menu.main]]
weight = 8
name = "Docs"
hasChildren = true

  [[Languages.es.menu.main]]
  parent = "Docs"
  name = "Guía para Desarrolladores"
  url = "dev"
  weight = 4

  [[Languages.es.menu.main]]
  parent = "Docs"
  name = "Guía para Usuarios"
  url = "user"
  weight = 1

  [[Languages.es.menu.main]]
  parent = "Docs"
  name = "Guía para Editores"
  url = "editor"
  weight = 2

  [[Languages.es.menu.main]]
  parent = "Docs"
  name = "Guía para Encargados de Colecciones"
  url = "coll_manager"
  weight = 3

################################### Franch Language ######################
[Languages.fr]
languageName = "Fr"
languageCode = "fr-fr"
weight = 3
#copyright = "Copyright © 2020 un thème Hugo par [Gethugothemes](https://gethugothemes.com/)"
copyright = "© 2021 [Symbiota Support Hub](https://symbiota.org)"

# banner
[Languages.fr.params.banner]
title = "Symbiota Documentation"
subtitle = "Growing archive of help files for one of the most popular Natural History content management systems"
bg_image = "images/annie-spratt-5cFwQ-WMcJU-unsplash.jpg"
placeholder = "Avoir une question? Il suffit de demander ici ou de saisir les termes"

# call to action
[Languages.fr.params.cta]
enable = true
title = "Vous n'avez pas trouvé de réponse à votre question?"
content = "Contactez-nous pour plus de détails sur les services supplémentaires et la tarification du travail personnalisé"
# call to action button
[Languages.fr.params.cta.button]
enable = true
label = "Contactez nous"
link = "contact"


################## french navigation #################
[[Languages.fr.menu.main]]
name = "Accueil"
url = "/"
weight = 1

[[Languages.fr.menu.main]]
name = "About"
url = "about"
weight = 2

[[Languages.fr.menu.main]]
name = "Faq"
url = "faq"
weight = 3

[[Languages.fr.menu.main]]
name = "Citing The Docs"
url = "citing"
weight = 4

[[Languages.fr.menu.main]]
name = "contact"
url = "contact"
weight = 5

# Dropdown menu
[[Languages.fr.menu.main]]
weight = 6
name = "docs"
hasChildren = true

  [[Languages.fr.menu.main]]
  parent = "docs"
  name = "Developer Guide"
  url = "dev"
  weight = 2

  [[Languages.fr.menu.main]]
  parent = "docs"
  name = "User Guide"
  url = "user"
  weight = 1
